### ISSUE TITLE
🚨 Error on try using Presentation Mode on production

### ISSUE THREAD

**Issue by gabrieldejesus** [sanity-io/hydrogen-sanity#101]
**Describe the bug**

For some reason even though I made all the configurations described in the documentation and even though it works locally. every time I try to test the `Presentation` mode in production with my final url I get the following error in the console:

```md
Unable to connect to visual editing. Make sure you've setup '@sanity/visual-editing' correctly.
```

But is anyone else getting this error and have you managed to find a solution?

**Screenshots**

![image](https://github.com/user-attachments/assets/c6cb9310-fd0e-434e-bd51-c30b9335dd95)

![image](https://github.com/user-attachments/assets/e2287f1a-25ab-4378-a5ba-6472aa0deeb1)

**Comment by puredazzle** [comment]
I guess this has to do with, #86 but I am also interested in a solution. There seems to be some error with the cookie.

**Comment by gabrieldejesus** [comment]
Yes, Sanity wasn't able to set the cookies, I managed to solve it by making this modification here:

In `session`, I change that:

```ts
const storage = createCookieSessionStorage({
  cookie: {
    name: "session",
    httpOnly: true,
    path: "/",
    sameSite: "lax",
    secrets,
  },
});
```

to this:

```ts
const storage = createCookieSessionStorage({
      cookie: {
        name: 'session',
        httpOnly: true,
        path: '/',
        sameSite: 'none',
        secure: true,
        secrets,
      },
    });
```

now works great ✨.

**Comment by puredazzle** [comment]
@gabrieldejesus I managed to fix it by using two clients, one for Shopify and one for Sanity. Like they have done here https://github.com/frontvibe/fluid/blob/main/app/lib/sanity/sanity.session.server.ts

**Comment by gabrieldejesus** [comment]
Hey @puredazzle  good to know about this solution too. mine was to use just one and change the session itself.

**Comment by madblokus** [comment]
@gabrieldejesus @puredazzle have you guys actually managed to deploy to oxygen after using the hydrogen-sanity client?

**Comment by puredazzle** [comment]
@madblokus yes, no problem.
