### ISSUE TITLE
Help Needed: Issues with Sanity Presentation Visual Editor Integration in Hydrogen (^4.1.0) with Shopify Hydrogen (2024.7.4)

### ISSUE THREAD

**Issue by musaa-muhsen** [sanity-io/hydrogen-sanity#102]
Hello all i was wondering if anyone can help us please we’re trying to get the Visual Editing/Presentation tool to work with Hydrogen im using:

 "hydrogen-sanity": "^4.1.0” and "@shopify/hydrogen": "2024.7.4”

We are trying get it to work locally initially however not been able to we’ve followed the hydrogen-sanity readme and this guide: 

https://www.sanity.io/learn/course/sanity-and-shopify-with-hydrogen/visual-editing-for-interactive-live-previews#s-528199a741ff

I added this to the loader and Layout to root.tsx - i don't understand what the preview real relevant has the way i set it as the docs has session related stuff: 

```tsx
 export async function loader(args: LoaderFunctionArgs) {
 ...,
 return defer({
 ...,
 preview: env.SANITY_PREVIEW_TOKEN
   ? {
       enabled: env.SANITY_PROJECT_ID ? true : false,
       token: env.SANITY_PREVIEW_TOKEN,
       studioUrl: "http://localhost:3333",
      }
   : undefined,
   
   }
   }
   
   
   export function Layout({children}: {children?: React.ReactNode}) {
     ...,
     return (
     ...,
     <body>
        {data ? (
          <Analytics.Provider
            cart={data.cart}
            shop={data.shop}
            consent={data.consent}
          >
                <SanityConfigProvider config={sanityConfig}>
                    <PageLayout sanityDataRoot={sanityData} {...data}>
                      {children}
                      {preview ? <VisualEditing /> : null}
                    </PageLayout> 
                </SanityConfigProvider>
          </Analytics.Provider>
        ) : (
          children
        )}
        <ScrollRestoration nonce={nonce} />
        <Scripts nonce={nonce} />
      </body>
   
   
   
```

I added this to the Content Security Policy in entry.server.tsx

```tsx
 defaultSrc: ['https://cdn.sanity.io'],
 connectSrc: [`https://${context.env.SANITY_PROJECT_ID}.api.sanity.io`, `wss://${context.env.SANITY_PROJECT_ID}.api.sanity.io`],
 frameAncestors: [`http://localhost:3333`, `'self'`],
```

Hydrogen has changed slightly since this in terms of “context”, “loaders” etc, i don’t understand how to access “sessions” in this situation or hows its relevant as ive seen it in the docs but the preview object i created does get fed to the client side.

In resource.preview.ts i added:

export {loader} from 'hydrogen-sanity/preview/route’

And finally in Sanity Studio i added any relevant CORS origin and this: 

```tsx
 presentationTool({
      previewUrl: {
        origin: "http://localhost:3000",
        preview: "/",
        previewMode: {
          enable: "/resource/preview",
        },
      },
    })
```

And locally im getting this, and when you click you get "Unable to enable preview mode. Please check your preview configuration”

<img width="607" alt="Screenshot 2024-09-26 at 12 16 04" src="https://github.com/user-attachments/assets/66f24e06-402f-4731-89c4-e02d55d6e84b">

Any help would be greatly appreciated by us, thank you.

**Comment by gabrieldejesus** [comment]
Hey @musaa-muhsen try change you `session.ts` file to this:

```ts
 const storage = createCookieSessionStorage({
      cookie: {
        name: 'session',
        httpOnly: true,
        path: '/',
        sameSite: 'none',
        secure: true,
        secrets,
      },
});
```

Let me know if this work for you.

**Comment by musaa-muhsen** [comment]
Hi @gabrieldejesus thanks for the response.

I tried that still getting the "Unable to enable preview mode...” 

When i console.log(args.context.sanity) in root.tsx i get this back: Object {
  loadQuery: ,
  client: SanityClient,
  preview: undefined
}

Perhaps this is part of the issue. I don't understand where to add to the preview logic because I added it here in root.tsx this way: 

```tsx
export async function loader(args: LoaderFunctionArgs) {
  // Start fetching non-critical data without blocking time to first byte
  const deferredData = loadDeferredData(args);

  // Await the critical data required to render initial state of the page
  const criticalData = await loadCriticalData(args);
  const {storefront, env, sanity} = args.context;

  console.log('args', args.context.sanity)

  return defer({
    ...deferredData,
    ...criticalData,
    publicStoreDomain: env.PUBLIC_STORE_DOMAIN,
    shop: getShopAnalytics({
      storefront,
      publicStorefrontId: env.PUBLIC_STOREFRONT_ID,
    }),
    consent: {
      checkoutDomain: env.PUBLIC_CHECKOUT_DOMAIN,
      storefrontAccessToken: env.PUBLIC_STOREFRONT_API_TOKEN,
    },
   preview: env.SANITY_PREVIEW_TOKEN
   ? {
       enabled: env.SANITY_PROJECT_ID ? true : false,
       token: env.SANITY_PREVIEW_TOKEN,
       studioUrl: "http://localhost:3333",
      }
   : undefined,
  });
}
```

**Comment by gabrieldejesus** [comment]
Yes @musaa-muhsen you need a value on `preview` object like this example:

```md
Object {
  enabled: true,
  token:  <some_token>,
  studioUrl: http://localhost:3333/staging
}
```

you should pass to your defer return the `sanity` object from your context as:

```ts
return defer({
 // other exports
 preview: context.sanity.preview?.enabled
});
```

this will allow the `VisualEditing` component from `hydrogen-sanity` work for you when you have a session.

**Comment by musaa-muhsen** [comment]
@gabrieldejesus thank you again for helping but still not working really frustrating haha. 

so I've added it like this i tried "/presentation" as it's on that route on sanity or just "/" or "/staging" unsure which one 

<img width="560" alt="Screenshot 2024-09-26 at 21 03 47" src="https://github.com/user-attachments/assets/8723c75d-12fb-4df7-8b7e-e955a65747c2">

I'm getting these error on the terminal unsure why i have made sure the .env are correct as well 

<img width="936" alt="Screenshot 2024-09-26 at 21 04 24" src="https://github.com/user-attachments/assets/3f208037-5d81-4bf3-87f9-838821195e6c">

Many thanks

**Comment by gabrieldejesus** [comment]
Hey @musaa-muhsen, it shouldn't be too frustrating, but I understand that setting up presentation mode in Hydrogen can be a bit challenging.

Looking at your errors, I believe you may not be configuring Sanity correctly in your context. Are you on [Sanity Slack](sanity-io-land.slack.com)? If so, let’s have a huddle so I can help you.

**Comment by musaa-muhsen** [comment]
Hi @gabrieldejesus that would be amazing obrigado. Please let me know what time suits you and hopefully we can talk then.

Here is my profile for sanity-io-land: https://sanity-io-land.slack.com/team/U024QR3NT5M

**Comment by puredazzle** [comment]
@musaa-muhsen @gabrieldejesus please let us know how / if you solved this issue!

**Comment by musaa-muhsen** [comment]
Hi @puredazzle no not yet unfortunately, it's still the same 500 error. I will keep you posted for sure.

**Comment by puredazzle** [comment]
@musaa-muhsen I managed to get it working by coping the functionality from https://github.com/frontvibe/fluid and specifically their SanitySession and how it works:

app/lib/sanity-session.js
```
import { createCookieSessionStorage } from "@shopify/remix-oxygen";

export class SanitySession {
  #session;
  #sessionStorage;

  constructor(sessionStorage, session) {
    this.#sessionStorage = sessionStorage;
    this.#session = session;
  }

  static async init(request, secrets) {
    const storage = createCookieSessionStorage({
      cookie: {
        httpOnly: true,
        name: "sanityPreview",
        // samesite must be none so Sanity Studio can access the cookie
        sameSite: "none",
        secrets,
        secure: true,
      },
    });

    const session = await storage.getSession(request.headers.get("Cookie"));

    return new this(storage, session);
  }

  commit() {
    return this.#sessionStorage.commitSession(this.#session);
  }

  destroy() {
    return this.#sessionStorage.destroySession(this.#session);
  }

  get has() {
    return this.#session.has;
  }

  get set() {
    return this.#session.set;
  }
}
```

app/lib/context.js
```
import { createSanityLoader } from "hydrogen-sanity";

import { createHydrogenContext, createWithCache } from "@shopify/hydrogen";

import { CART_QUERY_FRAGMENT } from "~/lib/fragments";
import { SanitySession } from "~/lib/sanity-session";
import { AppSession } from "~/lib/session";

/**
 * The context implementation is separate from server.ts
 * so that type can be extracted for AppLoadContext
 * @param {Request} request
 * @param {Env} env
 * @param {ExecutionContext} executionContext
 */
export async function createAppLoadContext(request, env, executionContext) {
  /**
   * Open a cache instance in the worker and a custom session instance.
   */
  if (!env?.SESSION_SECRET) {
    throw new Error("SESSION_SECRET environment variable is not set");
  }

  const waitUntil = executionContext.waitUntil.bind(executionContext);
  const [cache, session, sanitySession] = await Promise.all([
    caches.open("hydrogen"),
    AppSession.init(request, [env.SESSION_SECRET]),
    SanitySession.init(request, [env.SESSION_SECRET]),
  ]);

  const sanityPreviewMode = await sanitySession.has("previewMode");

  const withCache = createWithCache({
    cache,
    waitUntil,
    request,
  });

  const sanity = createSanityLoader({
    // Required:
    withCache,

    // Required:
    // Pass configuration options for Sanity client or an instantialized client
    client: {
      projectId: env.SANITY_PROJECT_ID,
      dataset: env.SANITY_DATASET,
      apiVersion: env.SANITY_API_VERSION || "2023-06-27",
      // eslint-disable-next-line no-undef
      useCdn: process.env.NODE_ENV === "production",
    },
    preview: env.SANITY_API_TOKEN
      ? {
          enabled: sanityPreviewMode,
          token: env.SANITY_API_TOKEN,
          studioUrl: env.SANITY_STUDIO_URL,
        }
      : undefined,
  });

  const hydrogenContext = createHydrogenContext({
    env,
    request,
    cache,
    waitUntil,
    session,
    i18n: { language: "SV", country: "SE" },
    cart: {
      queryFragment: CART_QUERY_FRAGMENT,
    },
  });

  return {
    ...hydrogenContext,
    sanity,
    sanitySession,
    // declare additional Remix loader context
  };
}
```

app/routes/sanity.preview.js
```
import { json, redirectDocument } from "@shopify/remix-oxygen";

import { notFound } from "~/lib/utils";

const ROOT_PATH = "/";

// POST will destroy the session.
export async function action({ context, request }) {
  const { sanitySession } = context;

  if (!(request.method === "POST" && sanitySession)) {
    return json({ message: "Method not allowed" }, 405);
  }

  const body = await request.formData();
  const slug = body.get("slug") ?? ROOT_PATH;
  const redirectTo = slug;

  return redirectDocument(redirectTo, {
    headers: {
      "Set-Cookie": await sanitySession.destroy(),
    },
  });
}

// Create a new session.
export async function loader({ context, request }) {
  const { env, sanitySession } = context;
  const useStega = env.SANITY_STUDIO_USE_PREVIEW_MODE === "true";

  if (!sanitySession) {
    notFound();
  }

  const { searchParams } = new URL(request.url);
  const slug = searchParams.get("slug") ?? ROOT_PATH;
  const redirectTo = slug + "?reload=true";

  sanitySession.set("previewMode", true);

  const headers = {
    "Set-Cookie": useStega ? await sanitySession.commit() : "",
  };

  return redirectDocument(redirectTo, {
    headers,
    status: 307,
  });
}
```

**Comment by musaa-muhsen** [comment]
thanks for sharing @puredazzle, I've implemented this code but I'm still having the same issue with the toggling of preview to navigate to other pages and just getting 404 page, sorry to be a pain for everyone. What would the root file be like? Would:

`{preview ? <VisualEditing /> : null} `

still be relevant as [fluid ](https://github.com/frontvibe/fluid) is kind of using the old way?

**Comment by musaa-muhsen** [comment]
The issue that i was having with the navigation turned out to be with my navigation data in preview mode and the outputted characters so for the sanity API data object pageOption "{
    "pageOption": "collections-view​​​​‌‍​‍​‍‌‍‌​‍‌‍‍‌‌‍‌‌‍‍‌‌‍‍​‍​‍​‍‍​‍​‍‌​‌‍​‌‌‍‍‌‍‍‌‌‌​‌‍‌​‍‍‌‍‍‌‌‍​‍​‍​‍​​‍​‍‌‍‍​‌​‍‌‍‌‌‌‍‌‍​‍​‍​‍‍​‍​‍‌‍‍​‌‌​‌‌​‌​​​‍‍​‍​‍‌‍​‌‍‌‍​‌‍​‌‌‍​‌‍‍​‌‍‌​‌‌​​‍‍​​​​​​​​​‍‌​​‌​‍‌‍‌‌‌​‌‍‌‌‌‍‍‌‌​‌‍​‌‌‌​‌‍‍‌‌‍‌‍‍​‍‌‍‍‌‌‍‍‌‌​‌‍‌‌‌‍‍‌‌​​‍‌‍‌‌‌‍‌​‌‍‍‌‌‌​​‍‌‍‌‌‍‌‍‌​‌‍‌‌​‌‌​​‌​‍‌‍‌‌‌​‌‍‌‌‌‍‍‌‌​‌‍​‌‌‌​‌‍‍‌‌‍‌‍‍​‍‌‍‍‌‌‍‌​​‌‌​‌‍‌‌‌‌​‌‌​‌‍‍‌‌‍‍‌‍‌‌​​‍‌‌​‌‍‌‌​​‌‍‌‌​‌‌​‌‍‌‌‌‌​‌‌​‌‍‍‌‌‍‍‌‍‌‌​​‍‌​​‌‍​‌‌‌​‌‍‍​​‌‌‍‍​‌‍‌‌‌‍​‌‌‍‌​‌‍‌‌‌​‍‌​​‌‍‌‌‌‍‌‍‌‌​​‍‌‌​‌‌‌​​‍‌‌‌‍‍‌‍‌‌‌‍‌​‍‌‌​​‌​‌​​‍‌‌​​‌​‌​​‍‌‌​​‍​​‍‌‍‌​‌‍​‌‍‌‍​​‍‌‍‌‌‌‍​‍​​​‌‍‌‍​‌‍​‌​​‌​‌‌​‍‌‌​​‍​​‍​‍‌‌​‌‌‌​‌​​‍‍‌​​‌‍​‌‌‍‌‌‍‌‌‌​‌​​‌‌​‌‍‍‌‌‍‌‍‍​‌‍​‍‌‍​‌‌​‌‍‌‌‌‌‌‌‌​‍‌‍​​‌‌‍‍​‌‌​‌‌​‌​​​‍‍​‍​‍‌‍​‌‍‌‍​‌‍​‌‌‍​‌‍‍​‌‍‌​‌‌​​‍‍​​​​​​​​​‍‌​​‌​‍‌‍‌‌‌​‌‍‌‌‌‍‍‌‌​‌‍​‌‌‌​‌‍‍‌‌‍‌‍‍​‍‌‍‌‍‍‌‌‍‌​​‌‌​‌‍‌‌‌‌​‌‌​‌‍‍‌‌‍‍‌‍‌‌​​‍‌‍‌‌​‌‍‌‌​​‌‍‌‌​‌‌​‌‍‌‌‌‌​‌‌​‌‍‍‌‌‍‍‌‍‌‌​​‍‌‍‌​​‌‍​‌‌‌​‌‍‍​​‌‌‍‍​‌‍‌‌‌‍​‌‌‍‌​‌‍‌‌‌​‍‌​​‌‍‌‌‌‍‌‍‌‌​‌‌‍‌‌‌‍‍‌‍‌‌‌‍‌​‌​‌​‍‌‌​​‍​​‍‌‍‌​‌‍​‌‍‌‍​​‍‌‍‌‌‌‍​‍​​​‌‍‌‍​‌‍​‌​​‌​‌‌​‍‌‌​​‍​​‍‌‌‌​‍‍‌​​‌‍​‌‌‍‌‌‍‌‌‌​‌​​‌‌​‌‍‍‌‌‍‌‍‍​‍​‍‌‌",
    "_key": "dcf2eb36ca15",
    "_type": "staticPageLink",
    "reference": null
}" added to Remix Link tag it was causing many lines of added characters something with "ZeroWidth" trailing so used regex to stop this:

`  const removeZeroWidthChars = (str: string) => {
    return str.replace(/[\u200B-\u200D\uFEFF]/g, '');
  };`

thank you @puredazzle and @gabrieldejesus for all the help i will now close this issue. Hopefully these insights mentioned here can help others.

**Comment by musaa-muhsen** [comment]
The issue that i was having with the navigation turned out to be with my navigation data in preview mode and the outputted characters so for the sanity API data object pageOption "{
"pageOption": "collections-view​​​​‌‍​‍​‍‌‍‌​‍‌‍‍‌‌‍‌‌‍‍‌‌‍‍​‍​‍​‍‍​‍​‍‌​‌‍​‌‌‍‍‌‍‍‌‌‌​‌‍‌​‍‍‌‍‍‌‌‍​‍​‍​‍​​‍​‍‌‍‍​‌​‍‌‍‌‌‌‍‌‍​‍​‍​‍‍​‍​‍‌‍‍​‌‌​‌‌​‌​​​‍‍​‍​‍‌‍​‌‍‌‍​‌‍​‌‌‍​‌‍‍​‌‍‌​‌‌​​‍‍​​​​​​​​​‍‌​​‌​‍‌‍‌‌‌​‌‍‌‌‌‍‍‌‌​‌‍​‌‌‌​‌‍‍‌‌‍‌‍‍​‍‌‍‍‌‌‍‍‌‌​‌‍‌‌‌‍‍‌‌​​‍‌‍‌‌‌‍‌​‌‍‍‌‌‌​​‍‌‍‌‌‍‌‍‌​‌‍‌‌​‌‌​​‌​‍‌‍‌‌‌​‌‍‌‌‌‍‍‌‌​‌‍​‌‌‌​‌‍‍‌‌‍‌‍‍​‍‌‍‍‌‌‍‌​​‌‌​‌‍‌‌‌‌​‌‌​‌‍‍‌‌‍‍‌‍‌‌​​‍‌‌​‌‍‌‌​​‌‍‌‌​‌‌​‌‍‌‌‌‌​‌‌​‌‍‍‌‌‍‍‌‍‌‌​​‍‌​​‌‍​‌‌‌​‌‍‍​​‌‌‍‍​‌‍‌‌‌‍​‌‌‍‌​‌‍‌‌‌​‍‌​​‌‍‌‌‌‍‌‍‌‌​​‍‌‌​‌‌‌​​‍‌‌‌‍‍‌‍‌‌‌‍‌​‍‌‌​​‌​‌​​‍‌‌​​‌​‌​​‍‌‌​​‍​​‍‌‍‌​‌‍​‌‍‌‍​​‍‌‍‌‌‌‍​‍​​​‌‍‌‍​‌‍​‌​​‌​‌‌​‍‌‌​​‍​​‍​‍‌‌​‌‌‌​‌​​‍‍‌​​‌‍​‌‌‍‌‌‍‌‌‌​‌​​‌‌​‌‍‍‌‌‍‌‍‍​‌‍​‍‌‍​‌‌​‌‍‌‌‌‌‌‌‌​‍‌‍​​‌‌‍‍​‌‌​‌‌​‌​​​‍‍​‍​‍‌‍​‌‍‌‍​‌‍​‌‌‍​‌‍‍​‌‍‌​‌‌​​‍‍​​​​​​​​​‍‌​​‌​‍‌‍‌‌‌​‌‍‌‌‌‍‍‌‌​‌‍​‌‌‌​‌‍‍‌‌‍‌‍‍​‍‌‍‌‍‍‌‌‍‌​​‌‌​‌‍‌‌‌‌​‌‌​‌‍‍‌‌‍‍‌‍‌‌​​‍‌‍‌‌​‌‍‌‌​​‌‍‌‌​‌‌​‌‍‌‌‌‌​‌‌​‌‍‍‌‌‍‍‌‍‌‌​​‍‌‍‌​​‌‍​‌‌‌​‌‍‍​​‌‌‍‍​‌‍‌‌‌‍​‌‌‍‌​‌‍‌‌‌​‍‌​​‌‍‌‌‌‍‌‍‌‌​‌‌‍‌‌‌‍‍‌‍‌‌‌‍‌​‌​‌​‍‌‌​​‍​​‍‌‍‌​‌‍​‌‍‌‍​​‍‌‍‌‌‌‍​‍​​​‌‍‌‍​‌‍​‌​​‌​‌‌​‍‌‌​​‍​​‍‌‌‌​‍‍‌​​‌‍​‌‌‍‌‌‍‌‌‌​‌​​‌‌​‌‍‍‌‌‍‌‍‍​‍​‍‌‌",
"_key": "dcf2eb36ca15",
"_type": "staticPageLink",
"reference": null
}" 

Which is added to Remix Link tag it was causing many lines of added characters something with "ZeroWidth" trailing so used regex to stop this:

 ` const removeZeroWidthChars = (str: string) => { return str.replace(/[\u200B-\u200D\uFEFF]/g, ''); };`

thank you @puredazzle and @gabrieldejesus for all the help i will now close this issue. Hopefully these insights mentioned here can help others.
