### ISSUE TITLE
Can't install it with the latest Hydrogen 2024.10.0

### ISSUE THREAD

**Issue by octave** [sanity-io/hydrogen-sanity#107]
When trying to install the latest version of `hydrogen-sanity` `4.2.1` with the latest `@shopify/hydrogen` `2024.10.0` the console is throwing dependencies errors:

``` 
npm error While resolving: tillak-hydrogen-sanity@2024.7.10
npm error Found: @shopify/hydrogen@2024.10.0
npm error node_modules/@shopify/hydrogen
npm error   @shopify/hydrogen@"^2024.10.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @shopify/hydrogen@"^2023.7.0 || ~2024.1.0 || ~2024.4.0 || ~2024.7.0" from hydrogen-sanity@4.2.1
npm error node_modules/hydrogen-sanity
npm error   hydrogen-sanity@"^4.2.1" from the root project
```

**Comment by nkgentile** [comment]
Looks like there's a breaking change in `@shopify/hydrogen` that affects this library. I'll draft a PR shortly.

https://github.com/Shopify/hydrogen/releases/tag/%40shopify/hydrogen%402024.10.0
