### ISSUE TITLE
4.2.0 loses type of loadQuery

### ISSUE THREAD

**Issue by dvnrsn** [sanity-io/hydrogen-sanity#109]
![CleanShot 2024-11-14 at 16 52 40@2x](https://github.com/user-attachments/assets/4771a6bc-4819-4095-92a7-3d8ba3c66722)

This interface is removed [here](https://github.com/sanity-io/hydrogen-sanity/commit/83e9a2e4f1eb12cfe84ece4a5661b14c45566c94)

```ts
declare module '@shopify/remix-oxygen' {
  /**
   * Declare local additions to the Remix loader context.
   */
  interface AppLoadContext {
    session: HydrogenSession
    sanity: SanityLoader
  }
}
```

I think the idea is that it should be added to AppLoadContext in `env.d.ts`. Do I have that right?

**Comment by nkgentile** [comment]
Yes, that's correct
