### ISSUE TITLE
Preview API route is not found on production (Oxygen)

### ISSUE THREAD

**Issue by Monolith-agency** [sanity-io/hydrogen-sanity#26]
Hi, I was configuring the preview panels in Sanity Studio when I realized that my production app was missing the API routes.

I know the preview route `/api/preview` works on the dev server and does make it to the build (works with `shopify hydrogen preview`).

But when I deploy to Oxygen the route is `Not found`.

Could it be that Oxygen doesn't handle those? Should I host somewhere else?

**Comment by czemu** [comment]
Hi @Monolith-agency, same problem here. Did you found any solution?

**Comment by Monolith-agency** [comment]
Hi @czemu I had forgotten to register an environment variable.

The API route did exist but was conditionally returning 404 when said variable was undefined

**Comment by czemu** [comment]
Ah, indeed. I had the same issue with a missing variable. Thanks!
