### ISSUE TITLE
Issue with preview cookie and the iframe pane

### ISSUE THREAD

**Issue by Monolith-agency** [sanity-io/hydrogen-sanity#27]
Hi, I was having an issue where my deployed staging was not entering preview mode in the iframe pane.

After some tweaking, I replicated the `PreviewSession` constructor and changed the cookie settings.

See [the current settings](https://github.com/sanity-io/hydrogen-sanity/blob/3a70ca36163c22b5f4d60cc4cbd25e3692aa50c1/src/preview/PreviewSession.ts#L15-L23)

My changes:

```ts
const storage = createCookieSessionStorage({
    cookie: {
        name: '__preview',
        httpOnly: true,
        sameSite: 'none', // <- here
        secure: true, // <- here
        secrets,
    },
})
```

This allowed the preview to work both in the iframe pane & outside.

Let me know if this is a good solution and if I should open a PR.
Thanks.

**Comment by czemu** [comment]
I had the same issue. These `__preview` cookie settings should be configurable somewhere.

A quick fix without messing with this package is to override the `Set-Cookie` header to add `Secure` flag and change the`SameSite` to `None`, like this:

```
// app/routes/api.preview.tsx
  
[...]
const customCookie = `${await sanity.preview.session.commit()}; Secure`.replace(/SameSite=Strict/, 'SameSite=None');

return redirect(searchParams.get('path') as string ?? ROOT_PATH, {
  status: 307,
  headers: {
    'Set-Cookie': customCookie,
  },
});
[...]
```

**Comment by nkgentile** [comment]
Yes, I can see the need to be able to configure the session cookie's options somewhere. I have created draft PR #35 that adds a configuration option to static method as one option.

Alternatively, one could also do the following:
```
const [cache, session, previewSession] = await Promise.all([
  caches?.open("hydrogen"),
  HydrogenSession.init(request, [env.SESSION_SECRET]),
  (async () => {
    const storage = createCookieSessionStorage({
      cookie: {
        name: "__preview",
        httpOnly: true,
        sameSite: "none", // <- here
        secure: true, // <- here
        secrets: [env.SESSION_SECRET],
      },
    });

    const session = await storage.getSession(request.headers.get("Cookie"));

    return new PreviewSession(storage, session);
  })(),
]);
```

I also should note here that one can pass _anything_ to `preview.session` when calling `createSanityClient`. Under the hood, it only calls `session.has('projectId')` to check whether the user has a preview session active.

Your question makes me wonder whether there's a better way to delegate this to the developer and have the package make less assumptions about the setup 🤔
