### ISSUE TITLE
Compatibility with Hydrogen 2023.10.x

### ISSUE THREAD

**Issue by MauiNuiVenison** [sanity-io/hydrogen-sanity#38]
When integrating hydrogen-sanity with @shopify/hydrogen 2023.10.2 I receive the following errors after referencing hydrogen-sanity in the server file.

`✘ [ERROR] Could not resolve "url"

    node_modules/eventsource/lib/eventsource.js:1:20:
      1 │ var parse = require('url').parse
        ╵                     ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "events"

    node_modules/eventsource/lib/eventsource.js:2:21:
      2 │ var events = require('events')
        ╵                      ~~~~~~~~

  The package "events" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "https"

    node_modules/eventsource/lib/eventsource.js:3:20:
      3 │ var https = require('https')
        ╵                     ~~~~~~~

  The package "https" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "http"

    node_modules/eventsource/lib/eventsource.js:4:19:
      4 │ var http = require('http')
        ╵                    ~~~~~~

  The package "http" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "util"

    node_modules/eventsource/lib/eventsource.js:5:19:
      5 │ var util = require('util')
        ╵                    ~~~~~~

  The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.`

I worked through a variety of solutions w/ no success. Has anyone else encountered this issue?
Thanks

**Comment by thomasKn** [comment]
Same issue here, I added node polyfills to remix config to make it work:
```ts
// remix.config.js

module.exports = {
  ...,
  serverNodeBuiltinsPolyfill: {
    modules: {
      http: true,
      https: true,
      events: true,
      url: true,
    }
  }
}
```

It would be better to completely remove Node.js built-in modules from the package as Hydrogen targets worker runtime. Adding node polyfills almost doubles the worker function size.

**Comment by MauiNuiVenison** [comment]
Eh, not the answer I was hoping for but ultimately, a decent step towards a functioning app.
Mahalo

**Comment by DennisKraaijeveld** [comment]
Ran into it as well. Will take your approach @thomasKn but I guess I'll use it only during development and wait for a new release which will fix it. I mean, doubling worker size will hurt loading times, right?

**Comment by thomasKn** [comment]
> Ran into it as well. Will take your approach @thomasKn but I guess I'll use it only during development and wait for a new release which will fix it. I mean, doubling worker size will hurt loading times, right?

Yes but there is also a [worker size limit](https://developers.cloudflare.com/workers/platform/limits/#worker-size) that you need to be careful about

**Comment by DennisKraaijeveld** [comment]
Isn't this eventsource package used by @sanity/client ? That could be a huge upset since I don't see that being fixed pretty soon..

**Comment by 1903-development-team** [comment]
It is being used by @sanity/client - always one step behind...
