### ISSUE TITLE
Perspective configuration issues

### ISSUE THREAD

**Issue by dvnrsn** [sanity-io/hydrogen-sanity#65]
Edit: the problem was I was missing the preview cookie it seems

**Describe the bug**

In trying to implement a `perspective: previewDrafts` I am unsuccessful. The content does not live update.

```js
config: {
  ...
  useCdn: false,
  token: env.SANITY_API_TOKEN,
  ignoreBrowserTokenWarning: true,
  perspective: 'previewDrafts',
```

I noticed from the readme that perhaps we should be going this in the `preview` config like so

```js
preview:
    env.SANITY_PREVIEW_SECRET && env.SANITY_API_TOKEN
      ? {
          session: previewSession,
          token: env.SANITY_API_TOKEN,
          perspective: 'previewDrafts',
        }
      : undefined,
```
but that also doesn't seem to work.

The only thing that works somewhat is to use raw in the config (with the token present as well)

```js
config: {
          token: env.SANITY_API_TOKEN,
          ignoreBrowserTokenWarning: true,
          perspective: 'raw'
```

**Expected behavior**

The UI updates any time I update sanity content and refresh the page (refire groq)

**Which versions of Sanity are you using?**

SANITY_API_VERSION="2023-06-15"

Run `sanity versions` in the terminal and copy-paste the result here.
(no CLI)

**What operating system are you using?**

MacOS Ventura

**Which versions of Node.js / npm are you running?**

node v20.11
npm v10.2.4

**Comment by dvnrsn** [comment]
Could this be because we need a cookie?

https://github.com/sanity-io/hydrogen-sanity?tab=readme-ov-file#entering-preview-mode

**Comment by nkgentile** [comment]
@dvnrsn, sounds like you were able to get things working-which is great!

I wanted to let you know that there is a new major version of `hydrogen-sanity` coming soon. If you're getting setup in a new storefront, you might want to check it out:
https://github.com/sanity-io/hydrogen-sanity/pull/64

**Comment by dvnrsn** [comment]
Nice, what's the target release date?

**Comment by nkgentile** [comment]
I've just published [the new version](https://github.com/sanity-io/hydrogen-sanity/releases)! 🚀

We'd be grateful for any feedback you have to share as you're getting this new version setup in your project. Thanks!

**Comment by dvnrsn** [comment]
@nkgentile I don't think this API is compatible with streaming and defer
https://remix.run/docs/en/main/guides/streaming#streaming

If `loadQuery` is giving us `QueryResponseInitial` instead of a promise of data, this will break the suspense/await pattern

```js
const data = context.sanity.loadQuery()

return defer({ data 
```

```jsx
const data = useLoaderData()

return <Suspense fallback={<div>loading</div>}>
  <Await resolve={data}>

**Comment by nkgentile** [comment]
`loadQuery` will return `Promise<QueryResponseInitial<T>>` as it is an asynchronous function:
https://github.com/sanity-io/hydrogen-sanity/blob/4e293a00959a449dd54f1516235855e072068a36/src/loader.ts#L77

**Comment by dvnrsn** [comment]
I understand but again the question is whether or not this will work with streaming + defer(). This doesn't seem to be the case as useQuery() does not accept a promise at its third param but suspense/await will need a promise.

```js
// loader: notice the absence of await for streaming
const initial = context.sanity.loadQuery()

return defer({ initial 
```

```js
  const {initial, query} = useLoaderData<typeof loader>();
  const {data, loading} = useQuery<SanityHomePage>(query, undefined, {initial});
  // useQuery doesn't accept a promise for initial but also now we have two sources of truth for the UI (data, initial)

  return <Suspense><Await resolve={initial}>
    {(data) => 
```
