### ISSUE TITLE
Cookie “__preview” has been rejected because it is in a cross-site 

### ISSUE THREAD

**Issue by dvnrsn** [sanity-io/hydrogen-sanity#69]
When I try to access my environment from sanity studio using [sanity-plugin-iframe-pane](https://www.sanity.io/plugins/iframe-pane). It seems we need a cookie set but that will not work in an iframe. Is there an alternative way to give content editors preview in the sanity studio?

**Comment by nkgentile** [comment]
The latest major version of this package is geared towards using Loaders and the Presentation tool to achieve live, visual editing of your storefront.

You can learn more in the [Visual Editing section of Sanity's documentation](https://www.sanity.io/docs/introduction-to-visual-editing)
