### ISSUE TITLE
Visual Editing breaking Oxygen deployment.

### ISSUE THREAD

**Issue by sanschaise** [sanity-io/hydrogen-sanity#70]
**Describe the bug**

If you add Visual Editing to a new vite based hydrogen setup following this [tutorial](https://www.sanity.io/learn/course/sanity-and-shopify-with-hydrogen/visual-editing-for-interactive-live-previews): You get the following error when deploying to Oxygen.

```
Error: Script startup exceeded CPU time limit.
```

If you remove Visual Editing component from root then the build works.

**To Reproduce**

Steps to reproduce the behavior: Install new version of Hydrogen then follow this  [tutorial](https://www.sanity.io/learn/course/sanity-and-shopify-with-hydrogen/visual-editing-for-interactive-live-previews)

**Expected behavior**

Oxygen should build.

**Screenshots**

**Which versions of Sanity are you using?**
 "hydrogen-sanity": "^4.0.2",
  "sanity": "^3.40.0",

**What operating system are you using?**
This is failing in the github oxygen build.

**Comment by nkgentile** [comment]
Ah, it looks like those materials are slightly out-of-date. Instead of importing from `@sanity/visual-editing/remix`, you should instead use:
```ts
import {VisualEditing} from 'hydrogen-sanity/visual-editing'
```
https://github.com/sanity-io/hydrogen-sanity?tab=readme-ov-file#visual-editing

**Comment by sanschaise** [comment]
@nkgentile Thank you but unfortunately the same error persists. Still seems to be the same package and code and still causes oxygen to fail deploying for the new hydrogen.

**Comment by voyageur-design** [comment]
chiming in to confirm that I am still having the same issue as well, have been using  `import {VisualEditing} from 'hydrogen-sanity/visual-editing'` since the latest hydrogen-sanity update.

**Comment by gabrieldejesus** [comment]
Hello @sanschaise did you define the variable: `SANITY_API_TOKEN` variable in your hydrogen project? you need to create a token in: [sanity.io/manage](https://www.sanity.io/manage).

**Comment by nkgentile** [comment]
@sanschaise, @voyageur-design, I published [a new patch version](https://github.com/sanity-io/hydrogen-sanity/releases/tag/v4.0.3) that should've (hopefully) resolved the issue you were experiencing. Thank you for reporting!
