### ISSUE TITLE
Thoughts on useQuery() API

### ISSUE THREAD

**Issue by dvnrsn** [sanity-io/hydrogen-sanity#78]
**Is your feature request related to a problem? Please describe.**
1. If given an initial value, useQuery should not yield data as potentially undefined
2. Could params be moved into options? Doing so would avoid the `undefined`

```ts
useQuery(QUERY, undefined, {initial})
```
**Describe the solution you'd like**
If destructuring data off data from useQuery, one should be confident it exists if initial value is provided
```ts
const {data} = useQuery(QUERY, undefined, {initial})

// is it possible this could avoid type error(i.e., data is never undefined)
const {title} = data
```
params in options
```ts
const {data} = useQuery(
  QUERY,
  { 
    params: { someData: 'cool' },
    initial: initialData,
  }

**Comment by nkgentile** [comment]
`useQuery` comes from the underlying loader package `@sanity/react-loader`:
https://github.com/sanity-io/visual-editing/blob/main/packages/react-loader
