### ISSUE TITLE
invisible Unicode characters from dropdown

### ISSUE THREAD

**Issue by dvnrsn** [sanity-io/hydrogen-sanity#79]
**Describe the bug**

With the upgrade to hydrogen-sanity 4 we're all of a sudden getting invisible unicode characters particularly from sanity dropdown fields. E.g.,

```js
 defineField({
      name: 'theme',
      title: 'theme',
      type: 'string',
      options: {
        layout: 'dropdown',
        list: [
          'dark'
```
![CleanShot 2024-05-23 at 11 52 59](https://github.com/sanity-io/hydrogen-sanity/assets/9112811/bf82be3a-76de-4d82-9f39-6defb635ae01)

This matters because we do a string comparison of the values in certain places and the strings no longer match

**To Reproduce**

1. Utilize string dropdown field in sanity
2. query field and use data in JS
3. notice string comparisons fail

**Expected behavior**

Invisible Unicode characters are stripped

**Screenshots**

**Which versions of Sanity are you using?**

    "sanity": "^3.24.1",

**What operating system are you using?**

MacOS Ventura

**Which versions of Node.js / npm are you running?**

10 and 20 respectively

**Comment by nkgentile** [comment]
Hey @dvnrsn, it sounds like you're encountering the invisible characters that the client uses to encode Content Source Maps into your responses. 

You can learn more about how this works here in the documentation:
https://www.sanity.io/docs/stega

**Comment by dvnrsn** [comment]
Beautiful. I was going to suggest my own cleanup function but it looks like this is the answer. Thank you Noah

```ts
import {vercelStegaCleanAll} from "@sanity/client/stega"

**Comment by nkgentile** [comment]
Another option is to filter those fields in the `stega` configuration:
https://github.com/sanity-io/client?tab=readme-ov-file#using-visual-editing-with-steganography
