### ISSUE TITLE
Upgrade Hydrogen dependencies to ^2024.7.2

### ISSUE THREAD

**Issue by theocerutti** [sanity-io/hydrogen-sanity#87]
Hello guys,

It seems the library doesn't work if I try to install it with hydrogen ^2024.7.2.  
However in your README you say `Sanity library requires @shopify/hydrogen >= ^2024.7.2` 

I already did a PR last time: https://github.com/sanity-io/hydrogen-sanity/issues/57, for the same issue.
Can we make the update so it also works for future hydrogen version ?

Thanks!!!!

**Comment by nkgentile** [comment]
Hey @theocerutti, the release last week bumped the peer dependency range to reflect the latest version of Hydrogen:
https://github.com/sanity-io/hydrogen-sanity/releases/tag/v4.0.5
