### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by johnark88** [sanity-io/hydrogen-sanity#98]
**Is your feature request related to a problem? Please describe.**

Due to Stega being enabled automatically, having a mention of stega-encoding would be great. I will admit, I missed it in the docs, but if its enabled automatically, might be nice to call it out. Comes in handy for comparing values and printing values in classNames. 

**Describe the solution you'd like**
Add a single sentance [here](https://github.com/sanity-io/hydrogen-sanity/blob/ba02af2ab538817f8092c611cd73817f8d4fa1a5/package/README.md?plain=1#L77) 

"While using preview mode, you may come across invisible characters, please make sure to checkout [stegaClean](https://www.sanity.io/docs/stega#71d682406b5e )"

Any chance we could disable it in the future? Thank you!

**Comment by nkgentile** [comment]
Sure thing! I've added a callout to the README with a link to the relevant documentation.
